# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='asr.proto',
  package='asr',
  syntax='proto3',
  serialized_pb=_b('\n\tasr.proto\x12\x03\x61sr\"+\n\x04Slot\x12\x11\n\tslot_name\x18\x01 \x01(\t\x12\x10\n\x08lexicons\x18\x02 \x03(\t\".\n\x07Lexicon\x12\x14\n\x0clexicon_name\x18\x01 \x01(\t\x12\r\n\x05words\x18\x02 \x03(\t\"\x87\x02\n\x05Skill\x12\x12\n\nskill_name\x18\x01 \x01(\t\x12(\n\nskill_type\x18\x02 \x01(\x0e\x32\x14.asr.Skill.SkillType\x12\x14\n\x0cparent_skill\x18\x03 \x01(\t\x12\x18\n\x10sentences_repeat\x18\x04 \x01(\x05\x12\x11\n\tsentences\x18\n \x03(\t\x12\x18\n\x05slots\x18\x0b \x03(\x0b\x32\t.asr.Slot\x12\x1e\n\x08lexicons\x18\x0c \x03(\x0b\x32\x0c.asr.Lexicon\"C\n\tSkillType\x12\x11\n\rSKILL_OFFLINE\x10\x00\x12\x11\n\rSKILL_BUILTIN\x10\x01\x12\x10\n\x0cSKILL_CUSTOM\x10\x02\"a\n\x0f\x41srTrainRequest\x12\x0e\n\x06\x61sr_id\x18\x01 \x01(\t\x12\"\n\ntrain_flag\x18\x02 \x01(\x0e\x32\x0e.asr.TrainFlag\x12\x1a\n\x06skills\x18\x03 \x03(\x0b\x32\n.asr.Skill\"\xd4\x02\n\x10\x41srTrainResponse\x12\x0e\n\x06\x61sr_id\x18\x01 \x01(\t\x12\"\n\ntrain_flag\x18\x02 \x01(\x0e\x32\x0e.asr.TrainFlag\x12\x33\n\nerror_code\x18\x03 \x01(\x0e\x32\x1f.asr.AsrTrainResponse.ErrorCode\x12\x11\n\terror_msg\x18\x04 \x01(\t\x12\x39\n\rresponse_type\x18\x05 \x01(\x0e\x32\".asr.AsrTrainResponse.ResponseType\x12\x16\n\x0eshare_file_dir\x18\x06 \x01(\t\x12\x1a\n\x12predict_train_time\x18\x07 \x01(\x05\"\"\n\x0cResponseType\x12\x12\n\x0eSHARE_FILE_SYS\x10\x00\"1\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07PREDICT\x10\x02*@\n\tTrainFlag\x12\x11\n\rTRAIN_BUILTIN\x10\x00\x12\x10\n\x0cTRAIN_CUSTOM\x10\x01\x12\x0e\n\nTRAIN_XBNF\x10\x02\x62\x06proto3')
)

_TRAINFLAG = _descriptor.EnumDescriptor(
  name='TrainFlag',
  full_name='asr.TrainFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAIN_BUILTIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAIN_CUSTOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAIN_XBNF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=819,
  serialized_end=883,
)
_sym_db.RegisterEnumDescriptor(_TRAINFLAG)

TrainFlag = enum_type_wrapper.EnumTypeWrapper(_TRAINFLAG)
TRAIN_BUILTIN = 0
TRAIN_CUSTOM = 1
TRAIN_XBNF = 2


_SKILL_SKILLTYPE = _descriptor.EnumDescriptor(
  name='SkillType',
  full_name='asr.Skill.SkillType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SKILL_OFFLINE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SKILL_BUILTIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SKILL_CUSTOM', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=308,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_SKILL_SKILLTYPE)

_ASRTRAINRESPONSE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='asr.AsrTrainResponse.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHARE_FILE_SYS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=732,
  serialized_end=766,
)
_sym_db.RegisterEnumDescriptor(_ASRTRAINRESPONSE_RESPONSETYPE)

_ASRTRAINRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='asr.AsrTrainResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREDICT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=768,
  serialized_end=817,
)
_sym_db.RegisterEnumDescriptor(_ASRTRAINRESPONSE_ERRORCODE)


_SLOT = _descriptor.Descriptor(
  name='Slot',
  full_name='asr.Slot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slot_name', full_name='asr.Slot.slot_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lexicons', full_name='asr.Slot.lexicons', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=61,
)


_LEXICON = _descriptor.Descriptor(
  name='Lexicon',
  full_name='asr.Lexicon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lexicon_name', full_name='asr.Lexicon.lexicon_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='asr.Lexicon.words', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=109,
)


_SKILL = _descriptor.Descriptor(
  name='Skill',
  full_name='asr.Skill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_name', full_name='asr.Skill.skill_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_type', full_name='asr.Skill.skill_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_skill', full_name='asr.Skill.parent_skill', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences_repeat', full_name='asr.Skill.sentences_repeat', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='asr.Skill.sentences', index=4,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slots', full_name='asr.Skill.slots', index=5,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lexicons', full_name='asr.Skill.lexicons', index=6,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SKILL_SKILLTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=375,
)


_ASRTRAINREQUEST = _descriptor.Descriptor(
  name='AsrTrainRequest',
  full_name='asr.AsrTrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asr_id', full_name='asr.AsrTrainRequest.asr_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_flag', full_name='asr.AsrTrainRequest.train_flag', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skills', full_name='asr.AsrTrainRequest.skills', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=474,
)


_ASRTRAINRESPONSE = _descriptor.Descriptor(
  name='AsrTrainResponse',
  full_name='asr.AsrTrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asr_id', full_name='asr.AsrTrainResponse.asr_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_flag', full_name='asr.AsrTrainResponse.train_flag', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='asr.AsrTrainResponse.error_code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='asr.AsrTrainResponse.error_msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_type', full_name='asr.AsrTrainResponse.response_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_file_dir', full_name='asr.AsrTrainResponse.share_file_dir', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predict_train_time', full_name='asr.AsrTrainResponse.predict_train_time', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ASRTRAINRESPONSE_RESPONSETYPE,
    _ASRTRAINRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=817,
)

_SKILL.fields_by_name['skill_type'].enum_type = _SKILL_SKILLTYPE
_SKILL.fields_by_name['slots'].message_type = _SLOT
_SKILL.fields_by_name['lexicons'].message_type = _LEXICON
_SKILL_SKILLTYPE.containing_type = _SKILL
_ASRTRAINREQUEST.fields_by_name['train_flag'].enum_type = _TRAINFLAG
_ASRTRAINREQUEST.fields_by_name['skills'].message_type = _SKILL
_ASRTRAINRESPONSE.fields_by_name['train_flag'].enum_type = _TRAINFLAG
_ASRTRAINRESPONSE.fields_by_name['error_code'].enum_type = _ASRTRAINRESPONSE_ERRORCODE
_ASRTRAINRESPONSE.fields_by_name['response_type'].enum_type = _ASRTRAINRESPONSE_RESPONSETYPE
_ASRTRAINRESPONSE_RESPONSETYPE.containing_type = _ASRTRAINRESPONSE
_ASRTRAINRESPONSE_ERRORCODE.containing_type = _ASRTRAINRESPONSE
DESCRIPTOR.message_types_by_name['Slot'] = _SLOT
DESCRIPTOR.message_types_by_name['Lexicon'] = _LEXICON
DESCRIPTOR.message_types_by_name['Skill'] = _SKILL
DESCRIPTOR.message_types_by_name['AsrTrainRequest'] = _ASRTRAINREQUEST
DESCRIPTOR.message_types_by_name['AsrTrainResponse'] = _ASRTRAINRESPONSE
DESCRIPTOR.enum_types_by_name['TrainFlag'] = _TRAINFLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Slot = _reflection.GeneratedProtocolMessageType('Slot', (_message.Message,), dict(
  DESCRIPTOR = _SLOT,
  __module__ = 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.Slot)
  ))
_sym_db.RegisterMessage(Slot)

Lexicon = _reflection.GeneratedProtocolMessageType('Lexicon', (_message.Message,), dict(
  DESCRIPTOR = _LEXICON,
  __module__ = 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.Lexicon)
  ))
_sym_db.RegisterMessage(Lexicon)

Skill = _reflection.GeneratedProtocolMessageType('Skill', (_message.Message,), dict(
  DESCRIPTOR = _SKILL,
  __module__ = 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.Skill)
  ))
_sym_db.RegisterMessage(Skill)

AsrTrainRequest = _reflection.GeneratedProtocolMessageType('AsrTrainRequest', (_message.Message,), dict(
  DESCRIPTOR = _ASRTRAINREQUEST,
  __module__ = 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.AsrTrainRequest)
  ))
_sym_db.RegisterMessage(AsrTrainRequest)

AsrTrainResponse = _reflection.GeneratedProtocolMessageType('AsrTrainResponse', (_message.Message,), dict(
  DESCRIPTOR = _ASRTRAINRESPONSE,
  __module__ = 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.AsrTrainResponse)
  ))
_sym_db.RegisterMessage(AsrTrainResponse)


# @@protoc_insertion_point(module_scope)
